server:
  port: 8081
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: iovu
    password: iovu
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fe183c91d096ae5fa1ce8d157c16e977
            client-secret: jnfusrWCnpQp9ZQe5W3NZhfhEnd5uivJ
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
          naver:
            client-id: j7UstD_wa5eX6DjumkIr
            client-secret: NruNE0JYIJ
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image  
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iovu.iovuback.domain, com.iovu.iovuback.dto

pdf:
  font:
    path: classpath:fonts/NanumGothic.ttf

  

