server:
  port: 8081 # ■ 8081 포트 유지

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1 # ■ 로컬 Oracle PDB(맥북 전용입니다요~~)
    username: iovu
    password: iovu

  mvc:
    view:
      prefix: /WEB-INF/views/ # ■ JSP 사용 시에만 필요
      suffix: .jsp #   REST-Only 프로젝트면 이 블록 삭제 가능

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iovu.iovuback.domain
  configuration:
    map-underscore-to-camel-case: false
    default-enum-type-handler:
      org.apache.ibatis.type.EnumTypeHandler
      # (enum → 문자열 매핑 명시적 설정)
# ↓ OAuth2·JWT 등 보안 설정은 실제로 사용 시 별도 프로필(dev/prod)로 분리 추천
#security:
#  oauth2:
#    client:
#      registration:
#        google:
#          client-id:  YOUR_GOOGLE_ID
#          client-secret: YOUR_GOOGLE_SECRET
#          scope:
#            - email
#            - profile
